addCommandHandler('notify', function(player)
    triggerClientEvent(player, "Durum", player, "aclık", "Karnın Aç Hemen Yemek Ye!")
            setTimer(function()
                triggerClientEvent(player, "Durum", player, "susuzluk", "Susamışsın Hemen Su İç!")
            end, 1, 1)
        end, 1, 1)
    end, 1, 1)
end)
